CREATE DATABASE product

CREATE TABLE Magasin(
IdMagasin INT IDENTITY(1,1) PRIMARY KEY,
Nom VARCHAR(50),
Adresse VARCHAR(100),
Telephone VARCHAR(15),
Email VARCHAR(75)
);

CREATE TABLE Produit (
CodeProduit INT IDENTITY(1,1) PRIMARY KEY,
Nom VARCHAR(50),
Description VARCHAR(200),
StockActuel INT,
PrixUnitaire FLOAT,
);